### ISSUE TITLE
Lemon is broken

### ISSUE THREAD

**Issue by CoelacanthusHex** [ChungZH/peach#2]
Upstream change link to https://github.com/Project-LemonLime/Project_LemonLime
and the version string have no prefix 'v'

**Comment by CoelacanthusHex** [comment]
ping @ChungZH

**Comment by zirnc** [comment]
嗷呜，这几天在机房关网集训，所以没看到 :sad:
现在还在机房，更新了一下，暂时没法测试。晚上回到家再修一下吧（

**Comment by zirnc** [comment]
fixed
